### ISSUE TITLE
Svelte (typescript) - How to import the USS API

### ISSUE THREAD

**Issue by Murphy-Joe** [CristianDavideConte/universalSmoothScroll#4]
Hello!  This API looks really well done and I'm excited to use it.  But first a dumb question.  I seem to be missing something to make my app recognize the `uss` object.

Here are the steps I've taken, along with screenshots to clarify.

1.  Downloaded the uss package via npm install
2. Copied the minified js file into my app's static directory
3. Included the minified js file in a script tag in my app.html's header

The caveat here is that I'm using Svelte-kit, which uses server side rendering.  Not sure if that is part of the equation or if I'm just missing something dumb.  

-Directory structure-
<img width="296" alt="image" src="https://user-images.githubusercontent.com/55860945/154565078-706a441d-1af0-4668-8eb1-6bc12deb1079.png">

-Script tag-
<img width="924" alt="image" src="https://user-images.githubusercontent.com/55860945/154564948-8c38d9cd-c0cb-421e-a9f2-07a839252596.png">

-`uss` object not recognized-
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/55860945/154564829-6cccc8b5-76d9-465f-bc55-4034361a33a0.png">

**Comment by CristianDavideConte** [comment]
Hi, thank you for reaching out!
From what I can see you correctly imported the API into your project and what you're dealing with may just be typescript warning you that you forgot to declare a global variable so it doesn't know if the `uss` object will be known at "compile time".

To show you what I mean, I've created a dummy Svelte project in which I tried to emulate and solve your problem.
<br/>

This is the initial situation of the `app.html` file (similar to yours): <br/>
![0) Initial Situation](https://user-images.githubusercontent.com/64142998/154674824-32dc7f64-69d2-46b6-921c-ef5a1470995f.png)
<br/>

This is a dummy `index.svelte` file in which a `test()` function is declared. 
This function is invoked whenever the `<h1>` text is clicked and its purpose is to test if the `uss` object can be used/found (spoiler: it cannot be found yet): <br/>
![1) Index with error](https://user-images.githubusercontent.com/64142998/154675003-63a05826-7b24-4204-a5ca-52bda37c2197.png)
<br/>

This is the typescript declarations-file (in your case I think it's called `global.d.ts`).
As you can see no global variables have been declared yet (the file is untouched so far):<br/>
![2) Typescript initial declaration](https://user-images.githubusercontent.com/64142998/154675957-9964bcfe-24bf-4acb-bff1-39b2f89a8c4f.png)
<br/>


This is the modified typescript declaration-file which now contains the needed declarations: <br/>
![3) Typescript declarations](https://user-images.githubusercontent.com/64142998/154677162-c0eedbb3-f016-4528-8edf-2db4930e3361.png)
<br/>

As you can see the `uss` object is now recognized inside our `index.svelte` file: <br/>
![4) Index without error](https://user-images.githubusercontent.com/64142998/154677416-d62d76cf-7431-408c-9eae-e0dade009bea.png)
<br/>

And the server-side-rendered page can now correctly use the API: <br/>
![5) Browser test](https://user-images.githubusercontent.com/64142998/154677543-899887ce-0719-42b4-a07d-d0bd02ef96ef.png)


I hope this solved you problem.
If it still doesn't work or you have some more questions about the API don't hesitate to contact me.
Have a nice day.

Cristian Davide Conte

**Comment by Murphy-Joe** [comment]
Very nice!  Thanks for the lesson and documentation!  

Works perfect for Chrome.  Not currently working in iOS Safari.   Just want to verify that it's meant to.  If so, I can do some tinkering to see what does / doesn't work.  


https://user-images.githubusercontent.com/55860945/154726878-f267ee2d-4dcc-49dd-b362-e9c08a1e3398.mov

**Comment by CristianDavideConte** [comment]
Mobile Safari on iOS is supported by the API and it should work the same way as in Chrome.
That may be a specific implementation problem or an API bug.

To see if the API works in you emulator you can go to the official playground or my website (both uses the API for smooth-scrolling) and try to click the anchors (they internally use the `uss.scrollIntoView` function).

Official Playground: https://cristiandavideconte.github.io/universalSmoothScroll/
My Website: https://cristiandavideconte.github.io/myPersonalWebPage/

**Comment by Murphy-Joe** [comment]
Good idea.   Both work fine in my emulator, so I'll have to tweak my implementation.  If/when I figure out what the hang up is I'll report back.  

Thanks for creating this great resource and your personal help, I hope this API continues gaining popularity!
